//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.1。
// 
namespace wsdlLib
{
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "HemoCommServiceSoap", Namespace = "http://tempuri.org/")]
    public partial class HemoCommService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback GetHisDataForHemoOperationCompleted;

        private System.Threading.SendOrPostCallback GetHisDeptmentOperationCompleted;

        private System.Threading.SendOrPostCallback GetHisDataUsersOperationCompleted;

        private System.Threading.SendOrPostCallback GetHisPatientsOperationCompleted;

        private System.Threading.SendOrPostCallback GetHisPatientOrdersOperationCompleted;

        private System.Threading.SendOrPostCallback GetLabDataByPatientsOperationCompleted;

        private System.Threading.SendOrPostCallback GetExamDataByPatientsOperationCompleted;

        /// <remarks/>
        public HemoCommService(string interFaceUrl)
        {
            this.Url = interFaceUrl; //System.Configuration.ConfigurationManager.AppSettings["HemoCommService"].ToString();
        }

        /// <remarks/>
        public event GetHisDataForHemoCompletedEventHandler GetHisDataForHemoCompleted;

        /// <remarks/>
        public event GetHisDeptmentCompletedEventHandler GetHisDeptmentCompleted;

        /// <remarks/>
        public event GetHisDataUsersCompletedEventHandler GetHisDataUsersCompleted;

        /// <remarks/>
        public event GetHisPatientsCompletedEventHandler GetHisPatientsCompleted;

        /// <remarks/>
        public event GetHisPatientOrdersCompletedEventHandler GetHisPatientOrdersCompleted;

        /// <remarks/>
        public event GetLabDataByPatientsCompletedEventHandler GetLabDataByPatientsCompleted;

        /// <remarks/>
        public event GetExamDataByPatientsCompletedEventHandler GetExamDataByPatientsCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHisDataForHemo", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetHisDataForHemo(string pMethodName, string pXMLString, string pOperatorId, string pCertificate)
        {
            object[] results = this.Invoke("GetHisDataForHemo", new object[] {
                        pMethodName,
                        pXMLString,
                        pOperatorId,
                        pCertificate});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetHisDataForHemo(string pMethodName, string pXMLString, string pOperatorId, string pCertificate, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetHisDataForHemo", new object[] {
                        pMethodName,
                        pXMLString,
                        pOperatorId,
                        pCertificate}, callback, asyncState);
        }

        /// <remarks/>
        public string EndGetHisDataForHemo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetHisDataForHemoAsync(string pMethodName, string pXMLString, string pOperatorId, string pCertificate)
        {
            this.GetHisDataForHemoAsync(pMethodName, pXMLString, pOperatorId, pCertificate, null);
        }

        /// <remarks/>
        public void GetHisDataForHemoAsync(string pMethodName, string pXMLString, string pOperatorId, string pCertificate, object userState)
        {
            if ((this.GetHisDataForHemoOperationCompleted == null))
            {
                this.GetHisDataForHemoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHisDataForHemoOperationCompleted);
            }
            this.InvokeAsync("GetHisDataForHemo", new object[] {
                        pMethodName,
                        pXMLString,
                        pOperatorId,
                        pCertificate}, this.GetHisDataForHemoOperationCompleted, userState);
        }

        private void OnGetHisDataForHemoOperationCompleted(object arg)
        {
            if ((this.GetHisDataForHemoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHisDataForHemoCompleted(this, new GetHisDataForHemoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHisDeptment", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetHisDeptment()
        {
            object[] results = this.Invoke("GetHisDeptment", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetHisDeptment(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetHisDeptment", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndGetHisDeptment(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetHisDeptmentAsync()
        {
            this.GetHisDeptmentAsync(null);
        }

        /// <remarks/>
        public void GetHisDeptmentAsync(object userState)
        {
            if ((this.GetHisDeptmentOperationCompleted == null))
            {
                this.GetHisDeptmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHisDeptmentOperationCompleted);
            }
            this.InvokeAsync("GetHisDeptment", new object[0], this.GetHisDeptmentOperationCompleted, userState);
        }

        private void OnGetHisDeptmentOperationCompleted(object arg)
        {
            if ((this.GetHisDeptmentCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHisDeptmentCompleted(this, new GetHisDeptmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHisDataUsers", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetHisDataUsers()
        {
            object[] results = this.Invoke("GetHisDataUsers", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetHisDataUsers(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetHisDataUsers", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndGetHisDataUsers(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetHisDataUsersAsync()
        {
            this.GetHisDataUsersAsync(null);
        }

        /// <remarks/>
        public void GetHisDataUsersAsync(object userState)
        {
            if ((this.GetHisDataUsersOperationCompleted == null))
            {
                this.GetHisDataUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHisDataUsersOperationCompleted);
            }
            this.InvokeAsync("GetHisDataUsers", new object[0], this.GetHisDataUsersOperationCompleted, userState);
        }

        private void OnGetHisDataUsersOperationCompleted(object arg)
        {
            if ((this.GetHisDataUsersCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHisDataUsersCompleted(this, new GetHisDataUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHisPatients", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetHisPatients(string pPatient)
        {
            object[] results = this.Invoke("GetHisPatients", new object[] {
                        pPatient});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetHisPatients(string pPatient, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetHisPatients", new object[] {
                        pPatient}, callback, asyncState);
        }

        /// <remarks/>
        public string EndGetHisPatients(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetHisPatientsAsync(string pPatient)
        {
            this.GetHisPatientsAsync(pPatient, null);
        }

        /// <remarks/>
        public void GetHisPatientsAsync(string pPatient, object userState)
        {
            if ((this.GetHisPatientsOperationCompleted == null))
            {
                this.GetHisPatientsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHisPatientsOperationCompleted);
            }
            this.InvokeAsync("GetHisPatients", new object[] {
                        pPatient}, this.GetHisPatientsOperationCompleted, userState);
        }

        private void OnGetHisPatientsOperationCompleted(object arg)
        {
            if ((this.GetHisPatientsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHisPatientsCompleted(this, new GetHisPatientsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHisPatientOrders", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetHisPatientOrders(string pPatientId, string pVisitId)
        {
            object[] results = this.Invoke("GetHisPatientOrders", new object[] {
                        pPatientId,
                        pVisitId});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetHisPatientOrders(string pPatientId, string pVisitId, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetHisPatientOrders", new object[] {
                        pPatientId,
                        pVisitId}, callback, asyncState);
        }

        /// <remarks/>
        public string EndGetHisPatientOrders(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetHisPatientOrdersAsync(string pPatientId, string pVisitId)
        {
            this.GetHisPatientOrdersAsync(pPatientId, pVisitId, null);
        }

        /// <remarks/>
        public void GetHisPatientOrdersAsync(string pPatientId, string pVisitId, object userState)
        {
            if ((this.GetHisPatientOrdersOperationCompleted == null))
            {
                this.GetHisPatientOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHisPatientOrdersOperationCompleted);
            }
            this.InvokeAsync("GetHisPatientOrders", new object[] {
                        pPatientId,
                        pVisitId}, this.GetHisPatientOrdersOperationCompleted, userState);
        }

        private void OnGetHisPatientOrdersOperationCompleted(object arg)
        {
            if ((this.GetHisPatientOrdersCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHisPatientOrdersCompleted(this, new GetHisPatientOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLabDataByPatients", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLabDataByPatients(string pPatientIds)
        {
            object[] results = this.Invoke("GetLabDataByPatients", new object[] {
                        pPatientIds});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetLabDataByPatients(string pPatientIds, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetLabDataByPatients", new object[] {
                        pPatientIds}, callback, asyncState);
        }

        /// <remarks/>
        public string EndGetLabDataByPatients(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetLabDataByPatientsAsync(string pPatientIds)
        {
            this.GetLabDataByPatientsAsync(pPatientIds, null);
        }

        /// <remarks/>
        public void GetLabDataByPatientsAsync(string pPatientIds, object userState)
        {
            if ((this.GetLabDataByPatientsOperationCompleted == null))
            {
                this.GetLabDataByPatientsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLabDataByPatientsOperationCompleted);
            }
            this.InvokeAsync("GetLabDataByPatients", new object[] {
                        pPatientIds}, this.GetLabDataByPatientsOperationCompleted, userState);
        }

        private void OnGetLabDataByPatientsOperationCompleted(object arg)
        {
            if ((this.GetLabDataByPatientsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLabDataByPatientsCompleted(this, new GetLabDataByPatientsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetExamDataByPatients", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetExamDataByPatients(string sPatientIds)
        {
            object[] results = this.Invoke("GetExamDataByPatients", new object[] {
                        sPatientIds});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetExamDataByPatients(string sPatientIds, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetExamDataByPatients", new object[] {
                        sPatientIds}, callback, asyncState);
        }

        /// <remarks/>
        public string EndGetExamDataByPatients(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetExamDataByPatientsAsync(string sPatientIds)
        {
            this.GetExamDataByPatientsAsync(sPatientIds, null);
        }

        /// <remarks/>
        public void GetExamDataByPatientsAsync(string sPatientIds, object userState)
        {
            if ((this.GetExamDataByPatientsOperationCompleted == null))
            {
                this.GetExamDataByPatientsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetExamDataByPatientsOperationCompleted);
            }
            this.InvokeAsync("GetExamDataByPatients", new object[] {
                        sPatientIds}, this.GetExamDataByPatientsOperationCompleted, userState);
        }

        private void OnGetExamDataByPatientsOperationCompleted(object arg)
        {
            if ((this.GetExamDataByPatientsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetExamDataByPatientsCompleted(this, new GetExamDataByPatientsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetHisDataForHemoCompletedEventHandler(object sender, GetHisDataForHemoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHisDataForHemoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetHisDataForHemoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetHisDeptmentCompletedEventHandler(object sender, GetHisDeptmentCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHisDeptmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetHisDeptmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetHisDataUsersCompletedEventHandler(object sender, GetHisDataUsersCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHisDataUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetHisDataUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetHisPatientsCompletedEventHandler(object sender, GetHisPatientsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHisPatientsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetHisPatientsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetHisPatientOrdersCompletedEventHandler(object sender, GetHisPatientOrdersCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHisPatientOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetHisPatientOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetLabDataByPatientsCompletedEventHandler(object sender, GetLabDataByPatientsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLabDataByPatientsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetLabDataByPatientsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetExamDataByPatientsCompletedEventHandler(object sender, GetExamDataByPatientsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetExamDataByPatientsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetExamDataByPatientsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
