CREATE OR REPLACE VIEW MED_VIEW_CHANGGUISHENGHUA_EXT AS
SELECT  T2.NAME as "姓名",
t2.hemodialysis_id as "透析号" ,
t.patient_id as "病人号",T2.TIME_TYPE as "病人来源",
t2.age as "年龄",
t.check_date as "检验日期",
t.COL_10 AS "*总蛋白(g/L)",
t.COL_11 AS  "*白蛋白(g/L)",
t.COL_12 AS  "球蛋白(g/L)",
t.COL_13 AS  "白蛋白/球蛋白",
t.COL_14 AS  "*总胆红素(umol/L)",
t.COL_15 AS  "*直接胆红素(umol/L)",
t.COL_16 AS  "间接胆红素(umol/L)",
t.COL_17 AS  "*谷氨酰转肽酶(U/L)",
t.COL_18 AS  "*碱性磷酸酶(U/L)",
t.COL_19 AS  "*谷丙转氨酶(U/L)",
t.COL_20 AS  "*谷草转氨酶(U/L)",
t.COL_21 AS  "谷草/谷丙",
t.COL_22 AS  "*肌酸激酶(U/L)",
t.COL_23 AS  "肌酸激酶同功酶(U/L)",
t.COL_24 AS  "*乳酸脱氢酶(U/L)",
t.COL_25 AS  "*尿素氮(mmol/L)",
t.COL_26 AS  "*肌酐(umol/L)",
t.COL_27 AS  "尿素氮/肌酐",
t.COL_28 AS  "*尿酸(umol/L)",
t.COL_29 AS  "*葡萄糖(mmol/L)",
t.COL_30 AS  "*甘油三脂(mmol/L)",
t.COL_31 AS  "*总胆固醇(mmol/L)",
t.COL_32 AS  "低密度脂蛋白(mmol/L)",
t.COL_33 AS  "载脂蛋白A1(g/L)",
t.COL_34 AS  "高密度脂蛋白(mmol/L)",
t.COL_35 AS  "载脂蛋白B(g/L)",
t.COL_36 AS  "载脂蛋白A1/B",
t.COL_37 AS  "*钠(mmol/L)",
t.COL_38 AS  "*钾(mmol/L)",
t.COL_39 AS  "*氯(mmol/L)",
t.COL_40 AS  "*血钙(mmol/L)",
t.COL_41 AS  "镁(mmol/L)",
t.COL_42 AS  "*磷(mmol/L)",
t.COL_43 AS  "二氧化碳(mmol/L)",
t.COL_44 AS  "阴离子间隙(mmol/L)",
t.COL_45 AS  "渗透压(mOSM/L)",
t2.input_code
FROM  MED_HIS_ROWTOCOL_END T  INNER JOIN MED_PATIENTS T2
ON T.PATIENT_ID = T2.PATIENT_ID
AND T2.IS_DELETE !=1
WHERE t.item_name ='常规生化全套检查';
