//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Hemo.Model {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("ErythropoietinModel")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class ErythropoietinModel : global::System.Data.DataSet {
        
        private MED_ERYTHROPOIETINDataTable tableMED_ERYTHROPOIETIN;
        
        private MED_ERYTHROPOIETIN_EXECDataTable tableMED_ERYTHROPOIETIN_EXEC;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public ErythropoietinModel() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected ErythropoietinModel(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["MED_ERYTHROPOIETIN"] != null)) {
                    base.Tables.Add(new MED_ERYTHROPOIETINDataTable(ds.Tables["MED_ERYTHROPOIETIN"]));
                }
                if ((ds.Tables["MED_ERYTHROPOIETIN_EXEC"] != null)) {
                    base.Tables.Add(new MED_ERYTHROPOIETIN_EXECDataTable(ds.Tables["MED_ERYTHROPOIETIN_EXEC"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public MED_ERYTHROPOIETINDataTable MED_ERYTHROPOIETIN {
            get {
                return this.tableMED_ERYTHROPOIETIN;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public MED_ERYTHROPOIETIN_EXECDataTable MED_ERYTHROPOIETIN_EXEC {
            get {
                return this.tableMED_ERYTHROPOIETIN_EXEC;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            ErythropoietinModel cln = ((ErythropoietinModel)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["MED_ERYTHROPOIETIN"] != null)) {
                    base.Tables.Add(new MED_ERYTHROPOIETINDataTable(ds.Tables["MED_ERYTHROPOIETIN"]));
                }
                if ((ds.Tables["MED_ERYTHROPOIETIN_EXEC"] != null)) {
                    base.Tables.Add(new MED_ERYTHROPOIETIN_EXECDataTable(ds.Tables["MED_ERYTHROPOIETIN_EXEC"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableMED_ERYTHROPOIETIN = ((MED_ERYTHROPOIETINDataTable)(base.Tables["MED_ERYTHROPOIETIN"]));
            if ((initTable == true)) {
                if ((this.tableMED_ERYTHROPOIETIN != null)) {
                    this.tableMED_ERYTHROPOIETIN.InitVars();
                }
            }
            this.tableMED_ERYTHROPOIETIN_EXEC = ((MED_ERYTHROPOIETIN_EXECDataTable)(base.Tables["MED_ERYTHROPOIETIN_EXEC"]));
            if ((initTable == true)) {
                if ((this.tableMED_ERYTHROPOIETIN_EXEC != null)) {
                    this.tableMED_ERYTHROPOIETIN_EXEC.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "ErythropoietinModel";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/ErythropoietinModel.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableMED_ERYTHROPOIETIN = new MED_ERYTHROPOIETINDataTable();
            base.Tables.Add(this.tableMED_ERYTHROPOIETIN);
            this.tableMED_ERYTHROPOIETIN_EXEC = new MED_ERYTHROPOIETIN_EXECDataTable();
            base.Tables.Add(this.tableMED_ERYTHROPOIETIN_EXEC);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeMED_ERYTHROPOIETIN() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeMED_ERYTHROPOIETIN_EXEC() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            ErythropoietinModel ds = new ErythropoietinModel();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void MED_ERYTHROPOIETINRowChangeEventHandler(object sender, MED_ERYTHROPOIETINRowChangeEvent e);
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void MED_ERYTHROPOIETIN_EXECRowChangeEventHandler(object sender, MED_ERYTHROPOIETIN_EXECRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class MED_ERYTHROPOIETINDataTable : global::System.Data.TypedTableBase<MED_ERYTHROPOIETINRow> {
            
            private global::System.Data.DataColumn columnERYTHROPOIETIN_ID;
            
            private global::System.Data.DataColumn columnDRUG_CODE;
            
            private global::System.Data.DataColumn columnQW;
            
            private global::System.Data.DataColumn columnTIME_TYPE;
            
            private global::System.Data.DataColumn columnFREQUENCY;
            
            private global::System.Data.DataColumn columnERYTHROPOIETIN_TYPE;
            
            private global::System.Data.DataColumn columnDRUG_MODE;
            
            private global::System.Data.DataColumn columnDOSAGE;
            
            private global::System.Data.DataColumn columnUNIT;
            
            private global::System.Data.DataColumn columnREMARK;
            
            private global::System.Data.DataColumn columnCREATE_USERID;
            
            private global::System.Data.DataColumn columnCREATE_TIME;
            
            private global::System.Data.DataColumn columnHEMODIALYSIS_ID;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public MED_ERYTHROPOIETINDataTable() {
                this.TableName = "MED_ERYTHROPOIETIN";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal MED_ERYTHROPOIETINDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected MED_ERYTHROPOIETINDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ERYTHROPOIETIN_IDColumn {
                get {
                    return this.columnERYTHROPOIETIN_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DRUG_CODEColumn {
                get {
                    return this.columnDRUG_CODE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn QWColumn {
                get {
                    return this.columnQW;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn TIME_TYPEColumn {
                get {
                    return this.columnTIME_TYPE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn FREQUENCYColumn {
                get {
                    return this.columnFREQUENCY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ERYTHROPOIETIN_TYPEColumn {
                get {
                    return this.columnERYTHROPOIETIN_TYPE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DRUG_MODEColumn {
                get {
                    return this.columnDRUG_MODE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DOSAGEColumn {
                get {
                    return this.columnDOSAGE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn UNITColumn {
                get {
                    return this.columnUNIT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn REMARKColumn {
                get {
                    return this.columnREMARK;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CREATE_USERIDColumn {
                get {
                    return this.columnCREATE_USERID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn CREATE_TIMEColumn {
                get {
                    return this.columnCREATE_TIME;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn HEMODIALYSIS_IDColumn {
                get {
                    return this.columnHEMODIALYSIS_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public MED_ERYTHROPOIETINRow this[int index] {
                get {
                    return ((MED_ERYTHROPOIETINRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event MED_ERYTHROPOIETINRowChangeEventHandler MED_ERYTHROPOIETINRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event MED_ERYTHROPOIETINRowChangeEventHandler MED_ERYTHROPOIETINRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event MED_ERYTHROPOIETINRowChangeEventHandler MED_ERYTHROPOIETINRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event MED_ERYTHROPOIETINRowChangeEventHandler MED_ERYTHROPOIETINRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddMED_ERYTHROPOIETINRow(MED_ERYTHROPOIETINRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public MED_ERYTHROPOIETINRow AddMED_ERYTHROPOIETINRow(string ERYTHROPOIETIN_ID, string DRUG_CODE, string QW, string TIME_TYPE, string FREQUENCY, string ERYTHROPOIETIN_TYPE, string DRUG_MODE, string DOSAGE, string UNIT, string REMARK, string CREATE_USERID, System.DateTime CREATE_TIME, string HEMODIALYSIS_ID) {
                MED_ERYTHROPOIETINRow rowMED_ERYTHROPOIETINRow = ((MED_ERYTHROPOIETINRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        ERYTHROPOIETIN_ID,
                        DRUG_CODE,
                        QW,
                        TIME_TYPE,
                        FREQUENCY,
                        ERYTHROPOIETIN_TYPE,
                        DRUG_MODE,
                        DOSAGE,
                        UNIT,
                        REMARK,
                        CREATE_USERID,
                        CREATE_TIME,
                        HEMODIALYSIS_ID};
                rowMED_ERYTHROPOIETINRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowMED_ERYTHROPOIETINRow);
                return rowMED_ERYTHROPOIETINRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public MED_ERYTHROPOIETINRow FindByERYTHROPOIETIN_ID(string ERYTHROPOIETIN_ID) {
                return ((MED_ERYTHROPOIETINRow)(this.Rows.Find(new object[] {
                            ERYTHROPOIETIN_ID})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                MED_ERYTHROPOIETINDataTable cln = ((MED_ERYTHROPOIETINDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new MED_ERYTHROPOIETINDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnERYTHROPOIETIN_ID = base.Columns["ERYTHROPOIETIN_ID"];
                this.columnDRUG_CODE = base.Columns["DRUG_CODE"];
                this.columnQW = base.Columns["QW"];
                this.columnTIME_TYPE = base.Columns["TIME_TYPE"];
                this.columnFREQUENCY = base.Columns["FREQUENCY"];
                this.columnERYTHROPOIETIN_TYPE = base.Columns["ERYTHROPOIETIN_TYPE"];
                this.columnDRUG_MODE = base.Columns["DRUG_MODE"];
                this.columnDOSAGE = base.Columns["DOSAGE"];
                this.columnUNIT = base.Columns["UNIT"];
                this.columnREMARK = base.Columns["REMARK"];
                this.columnCREATE_USERID = base.Columns["CREATE_USERID"];
                this.columnCREATE_TIME = base.Columns["CREATE_TIME"];
                this.columnHEMODIALYSIS_ID = base.Columns["HEMODIALYSIS_ID"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnERYTHROPOIETIN_ID = new global::System.Data.DataColumn("ERYTHROPOIETIN_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnERYTHROPOIETIN_ID);
                this.columnDRUG_CODE = new global::System.Data.DataColumn("DRUG_CODE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDRUG_CODE);
                this.columnQW = new global::System.Data.DataColumn("QW", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQW);
                this.columnTIME_TYPE = new global::System.Data.DataColumn("TIME_TYPE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTIME_TYPE);
                this.columnFREQUENCY = new global::System.Data.DataColumn("FREQUENCY", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFREQUENCY);
                this.columnERYTHROPOIETIN_TYPE = new global::System.Data.DataColumn("ERYTHROPOIETIN_TYPE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnERYTHROPOIETIN_TYPE);
                this.columnDRUG_MODE = new global::System.Data.DataColumn("DRUG_MODE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDRUG_MODE);
                this.columnDOSAGE = new global::System.Data.DataColumn("DOSAGE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDOSAGE);
                this.columnUNIT = new global::System.Data.DataColumn("UNIT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUNIT);
                this.columnREMARK = new global::System.Data.DataColumn("REMARK", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnREMARK);
                this.columnCREATE_USERID = new global::System.Data.DataColumn("CREATE_USERID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCREATE_USERID);
                this.columnCREATE_TIME = new global::System.Data.DataColumn("CREATE_TIME", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCREATE_TIME);
                this.columnHEMODIALYSIS_ID = new global::System.Data.DataColumn("HEMODIALYSIS_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnHEMODIALYSIS_ID);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnERYTHROPOIETIN_ID}, true));
                this.columnERYTHROPOIETIN_ID.AllowDBNull = false;
                this.columnERYTHROPOIETIN_ID.Unique = true;
                this.columnERYTHROPOIETIN_ID.MaxLength = 36;
                this.columnDRUG_CODE.MaxLength = 10;
                this.columnQW.MaxLength = 50;
                this.columnTIME_TYPE.MaxLength = 50;
                this.columnFREQUENCY.MaxLength = 50;
                this.columnERYTHROPOIETIN_TYPE.MaxLength = 50;
                this.columnDRUG_MODE.MaxLength = 50;
                this.columnDOSAGE.MaxLength = 50;
                this.columnUNIT.MaxLength = 50;
                this.columnREMARK.MaxLength = 500;
                this.columnCREATE_USERID.AllowDBNull = false;
                this.columnCREATE_USERID.MaxLength = 36;
                this.columnCREATE_TIME.AllowDBNull = false;
                this.columnHEMODIALYSIS_ID.AllowDBNull = false;
                this.columnHEMODIALYSIS_ID.MaxLength = 40;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public MED_ERYTHROPOIETINRow NewMED_ERYTHROPOIETINRow() {
                return ((MED_ERYTHROPOIETINRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new MED_ERYTHROPOIETINRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(MED_ERYTHROPOIETINRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.MED_ERYTHROPOIETINRowChanged != null)) {
                    this.MED_ERYTHROPOIETINRowChanged(this, new MED_ERYTHROPOIETINRowChangeEvent(((MED_ERYTHROPOIETINRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.MED_ERYTHROPOIETINRowChanging != null)) {
                    this.MED_ERYTHROPOIETINRowChanging(this, new MED_ERYTHROPOIETINRowChangeEvent(((MED_ERYTHROPOIETINRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.MED_ERYTHROPOIETINRowDeleted != null)) {
                    this.MED_ERYTHROPOIETINRowDeleted(this, new MED_ERYTHROPOIETINRowChangeEvent(((MED_ERYTHROPOIETINRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.MED_ERYTHROPOIETINRowDeleting != null)) {
                    this.MED_ERYTHROPOIETINRowDeleting(this, new MED_ERYTHROPOIETINRowChangeEvent(((MED_ERYTHROPOIETINRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveMED_ERYTHROPOIETINRow(MED_ERYTHROPOIETINRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                ErythropoietinModel ds = new ErythropoietinModel();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "MED_ERYTHROPOIETINDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class MED_ERYTHROPOIETIN_EXECDataTable : global::System.Data.TypedTableBase<MED_ERYTHROPOIETIN_EXECRow> {
            
            private global::System.Data.DataColumn columnEXEC_ID;
            
            private global::System.Data.DataColumn columnERYTHROPOIETIN_ID;
            
            private global::System.Data.DataColumn columnREMARK;
            
            private global::System.Data.DataColumn columnNURSE;
            
            private global::System.Data.DataColumn columnEXCUTE_DATE;
            
            private global::System.Data.DataColumn columnDRUG_ORDER_ID;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public MED_ERYTHROPOIETIN_EXECDataTable() {
                this.TableName = "MED_ERYTHROPOIETIN_EXEC";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal MED_ERYTHROPOIETIN_EXECDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected MED_ERYTHROPOIETIN_EXECDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn EXEC_IDColumn {
                get {
                    return this.columnEXEC_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ERYTHROPOIETIN_IDColumn {
                get {
                    return this.columnERYTHROPOIETIN_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn REMARKColumn {
                get {
                    return this.columnREMARK;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn NURSEColumn {
                get {
                    return this.columnNURSE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn EXCUTE_DATEColumn {
                get {
                    return this.columnEXCUTE_DATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn DRUG_ORDER_IDColumn {
                get {
                    return this.columnDRUG_ORDER_ID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public MED_ERYTHROPOIETIN_EXECRow this[int index] {
                get {
                    return ((MED_ERYTHROPOIETIN_EXECRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event MED_ERYTHROPOIETIN_EXECRowChangeEventHandler MED_ERYTHROPOIETIN_EXECRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event MED_ERYTHROPOIETIN_EXECRowChangeEventHandler MED_ERYTHROPOIETIN_EXECRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event MED_ERYTHROPOIETIN_EXECRowChangeEventHandler MED_ERYTHROPOIETIN_EXECRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event MED_ERYTHROPOIETIN_EXECRowChangeEventHandler MED_ERYTHROPOIETIN_EXECRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddMED_ERYTHROPOIETIN_EXECRow(MED_ERYTHROPOIETIN_EXECRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public MED_ERYTHROPOIETIN_EXECRow AddMED_ERYTHROPOIETIN_EXECRow(string EXEC_ID, string ERYTHROPOIETIN_ID, string REMARK, string NURSE, System.DateTime EXCUTE_DATE, string DRUG_ORDER_ID) {
                MED_ERYTHROPOIETIN_EXECRow rowMED_ERYTHROPOIETIN_EXECRow = ((MED_ERYTHROPOIETIN_EXECRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        EXEC_ID,
                        ERYTHROPOIETIN_ID,
                        REMARK,
                        NURSE,
                        EXCUTE_DATE,
                        DRUG_ORDER_ID};
                rowMED_ERYTHROPOIETIN_EXECRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowMED_ERYTHROPOIETIN_EXECRow);
                return rowMED_ERYTHROPOIETIN_EXECRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public MED_ERYTHROPOIETIN_EXECRow FindByEXEC_ID(string EXEC_ID) {
                return ((MED_ERYTHROPOIETIN_EXECRow)(this.Rows.Find(new object[] {
                            EXEC_ID})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                MED_ERYTHROPOIETIN_EXECDataTable cln = ((MED_ERYTHROPOIETIN_EXECDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new MED_ERYTHROPOIETIN_EXECDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnEXEC_ID = base.Columns["EXEC_ID"];
                this.columnERYTHROPOIETIN_ID = base.Columns["ERYTHROPOIETIN_ID"];
                this.columnREMARK = base.Columns["REMARK"];
                this.columnNURSE = base.Columns["NURSE"];
                this.columnEXCUTE_DATE = base.Columns["EXCUTE_DATE"];
                this.columnDRUG_ORDER_ID = base.Columns["DRUG_ORDER_ID"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnEXEC_ID = new global::System.Data.DataColumn("EXEC_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEXEC_ID);
                this.columnERYTHROPOIETIN_ID = new global::System.Data.DataColumn("ERYTHROPOIETIN_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnERYTHROPOIETIN_ID);
                this.columnREMARK = new global::System.Data.DataColumn("REMARK", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnREMARK);
                this.columnNURSE = new global::System.Data.DataColumn("NURSE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNURSE);
                this.columnEXCUTE_DATE = new global::System.Data.DataColumn("EXCUTE_DATE", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEXCUTE_DATE);
                this.columnDRUG_ORDER_ID = new global::System.Data.DataColumn("DRUG_ORDER_ID", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDRUG_ORDER_ID);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnEXEC_ID}, true));
                this.columnEXEC_ID.AllowDBNull = false;
                this.columnEXEC_ID.Unique = true;
                this.columnEXEC_ID.MaxLength = 36;
                this.columnERYTHROPOIETIN_ID.AllowDBNull = false;
                this.columnERYTHROPOIETIN_ID.MaxLength = 36;
                this.columnREMARK.MaxLength = 500;
                this.columnNURSE.AllowDBNull = false;
                this.columnNURSE.MaxLength = 40;
                this.columnEXCUTE_DATE.AllowDBNull = false;
                this.columnDRUG_ORDER_ID.AllowDBNull = false;
                this.columnDRUG_ORDER_ID.MaxLength = 20;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public MED_ERYTHROPOIETIN_EXECRow NewMED_ERYTHROPOIETIN_EXECRow() {
                return ((MED_ERYTHROPOIETIN_EXECRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new MED_ERYTHROPOIETIN_EXECRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(MED_ERYTHROPOIETIN_EXECRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.MED_ERYTHROPOIETIN_EXECRowChanged != null)) {
                    this.MED_ERYTHROPOIETIN_EXECRowChanged(this, new MED_ERYTHROPOIETIN_EXECRowChangeEvent(((MED_ERYTHROPOIETIN_EXECRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.MED_ERYTHROPOIETIN_EXECRowChanging != null)) {
                    this.MED_ERYTHROPOIETIN_EXECRowChanging(this, new MED_ERYTHROPOIETIN_EXECRowChangeEvent(((MED_ERYTHROPOIETIN_EXECRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.MED_ERYTHROPOIETIN_EXECRowDeleted != null)) {
                    this.MED_ERYTHROPOIETIN_EXECRowDeleted(this, new MED_ERYTHROPOIETIN_EXECRowChangeEvent(((MED_ERYTHROPOIETIN_EXECRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.MED_ERYTHROPOIETIN_EXECRowDeleting != null)) {
                    this.MED_ERYTHROPOIETIN_EXECRowDeleting(this, new MED_ERYTHROPOIETIN_EXECRowChangeEvent(((MED_ERYTHROPOIETIN_EXECRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveMED_ERYTHROPOIETIN_EXECRow(MED_ERYTHROPOIETIN_EXECRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                ErythropoietinModel ds = new ErythropoietinModel();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "MED_ERYTHROPOIETIN_EXECDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class MED_ERYTHROPOIETINRow : global::System.Data.DataRow {
            
            private MED_ERYTHROPOIETINDataTable tableMED_ERYTHROPOIETIN;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal MED_ERYTHROPOIETINRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableMED_ERYTHROPOIETIN = ((MED_ERYTHROPOIETINDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ERYTHROPOIETIN_ID {
                get {
                    return ((string)(this[this.tableMED_ERYTHROPOIETIN.ERYTHROPOIETIN_IDColumn]));
                }
                set {
                    this[this.tableMED_ERYTHROPOIETIN.ERYTHROPOIETIN_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DRUG_CODE {
                get {
                    try {
                        return ((string)(this[this.tableMED_ERYTHROPOIETIN.DRUG_CODEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“MED_ERYTHROPOIETIN”中列“DRUG_CODE”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableMED_ERYTHROPOIETIN.DRUG_CODEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string QW {
                get {
                    try {
                        return ((string)(this[this.tableMED_ERYTHROPOIETIN.QWColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“MED_ERYTHROPOIETIN”中列“QW”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableMED_ERYTHROPOIETIN.QWColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string TIME_TYPE {
                get {
                    try {
                        return ((string)(this[this.tableMED_ERYTHROPOIETIN.TIME_TYPEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“MED_ERYTHROPOIETIN”中列“TIME_TYPE”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableMED_ERYTHROPOIETIN.TIME_TYPEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string FREQUENCY {
                get {
                    try {
                        return ((string)(this[this.tableMED_ERYTHROPOIETIN.FREQUENCYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“MED_ERYTHROPOIETIN”中列“FREQUENCY”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableMED_ERYTHROPOIETIN.FREQUENCYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ERYTHROPOIETIN_TYPE {
                get {
                    try {
                        return ((string)(this[this.tableMED_ERYTHROPOIETIN.ERYTHROPOIETIN_TYPEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“MED_ERYTHROPOIETIN”中列“ERYTHROPOIETIN_TYPE”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableMED_ERYTHROPOIETIN.ERYTHROPOIETIN_TYPEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DRUG_MODE {
                get {
                    try {
                        return ((string)(this[this.tableMED_ERYTHROPOIETIN.DRUG_MODEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“MED_ERYTHROPOIETIN”中列“DRUG_MODE”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableMED_ERYTHROPOIETIN.DRUG_MODEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DOSAGE {
                get {
                    try {
                        return ((string)(this[this.tableMED_ERYTHROPOIETIN.DOSAGEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“MED_ERYTHROPOIETIN”中列“DOSAGE”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableMED_ERYTHROPOIETIN.DOSAGEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string UNIT {
                get {
                    try {
                        return ((string)(this[this.tableMED_ERYTHROPOIETIN.UNITColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“MED_ERYTHROPOIETIN”中列“UNIT”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableMED_ERYTHROPOIETIN.UNITColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string REMARK {
                get {
                    try {
                        return ((string)(this[this.tableMED_ERYTHROPOIETIN.REMARKColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“MED_ERYTHROPOIETIN”中列“REMARK”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableMED_ERYTHROPOIETIN.REMARKColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string CREATE_USERID {
                get {
                    return ((string)(this[this.tableMED_ERYTHROPOIETIN.CREATE_USERIDColumn]));
                }
                set {
                    this[this.tableMED_ERYTHROPOIETIN.CREATE_USERIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime CREATE_TIME {
                get {
                    return ((global::System.DateTime)(this[this.tableMED_ERYTHROPOIETIN.CREATE_TIMEColumn]));
                }
                set {
                    this[this.tableMED_ERYTHROPOIETIN.CREATE_TIMEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string HEMODIALYSIS_ID {
                get {
                    return ((string)(this[this.tableMED_ERYTHROPOIETIN.HEMODIALYSIS_IDColumn]));
                }
                set {
                    this[this.tableMED_ERYTHROPOIETIN.HEMODIALYSIS_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDRUG_CODENull() {
                return this.IsNull(this.tableMED_ERYTHROPOIETIN.DRUG_CODEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDRUG_CODENull() {
                this[this.tableMED_ERYTHROPOIETIN.DRUG_CODEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsQWNull() {
                return this.IsNull(this.tableMED_ERYTHROPOIETIN.QWColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetQWNull() {
                this[this.tableMED_ERYTHROPOIETIN.QWColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsTIME_TYPENull() {
                return this.IsNull(this.tableMED_ERYTHROPOIETIN.TIME_TYPEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetTIME_TYPENull() {
                this[this.tableMED_ERYTHROPOIETIN.TIME_TYPEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsFREQUENCYNull() {
                return this.IsNull(this.tableMED_ERYTHROPOIETIN.FREQUENCYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetFREQUENCYNull() {
                this[this.tableMED_ERYTHROPOIETIN.FREQUENCYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsERYTHROPOIETIN_TYPENull() {
                return this.IsNull(this.tableMED_ERYTHROPOIETIN.ERYTHROPOIETIN_TYPEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetERYTHROPOIETIN_TYPENull() {
                this[this.tableMED_ERYTHROPOIETIN.ERYTHROPOIETIN_TYPEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDRUG_MODENull() {
                return this.IsNull(this.tableMED_ERYTHROPOIETIN.DRUG_MODEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDRUG_MODENull() {
                this[this.tableMED_ERYTHROPOIETIN.DRUG_MODEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsDOSAGENull() {
                return this.IsNull(this.tableMED_ERYTHROPOIETIN.DOSAGEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetDOSAGENull() {
                this[this.tableMED_ERYTHROPOIETIN.DOSAGEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsUNITNull() {
                return this.IsNull(this.tableMED_ERYTHROPOIETIN.UNITColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetUNITNull() {
                this[this.tableMED_ERYTHROPOIETIN.UNITColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsREMARKNull() {
                return this.IsNull(this.tableMED_ERYTHROPOIETIN.REMARKColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetREMARKNull() {
                this[this.tableMED_ERYTHROPOIETIN.REMARKColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class MED_ERYTHROPOIETIN_EXECRow : global::System.Data.DataRow {
            
            private MED_ERYTHROPOIETIN_EXECDataTable tableMED_ERYTHROPOIETIN_EXEC;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal MED_ERYTHROPOIETIN_EXECRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableMED_ERYTHROPOIETIN_EXEC = ((MED_ERYTHROPOIETIN_EXECDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string EXEC_ID {
                get {
                    return ((string)(this[this.tableMED_ERYTHROPOIETIN_EXEC.EXEC_IDColumn]));
                }
                set {
                    this[this.tableMED_ERYTHROPOIETIN_EXEC.EXEC_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string ERYTHROPOIETIN_ID {
                get {
                    return ((string)(this[this.tableMED_ERYTHROPOIETIN_EXEC.ERYTHROPOIETIN_IDColumn]));
                }
                set {
                    this[this.tableMED_ERYTHROPOIETIN_EXEC.ERYTHROPOIETIN_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string REMARK {
                get {
                    try {
                        return ((string)(this[this.tableMED_ERYTHROPOIETIN_EXEC.REMARKColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("表“MED_ERYTHROPOIETIN_EXEC”中列“REMARK”的值为 DBNull。", e);
                    }
                }
                set {
                    this[this.tableMED_ERYTHROPOIETIN_EXEC.REMARKColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string NURSE {
                get {
                    return ((string)(this[this.tableMED_ERYTHROPOIETIN_EXEC.NURSEColumn]));
                }
                set {
                    this[this.tableMED_ERYTHROPOIETIN_EXEC.NURSEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.DateTime EXCUTE_DATE {
                get {
                    return ((global::System.DateTime)(this[this.tableMED_ERYTHROPOIETIN_EXEC.EXCUTE_DATEColumn]));
                }
                set {
                    this[this.tableMED_ERYTHROPOIETIN_EXEC.EXCUTE_DATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string DRUG_ORDER_ID {
                get {
                    return ((string)(this[this.tableMED_ERYTHROPOIETIN_EXEC.DRUG_ORDER_IDColumn]));
                }
                set {
                    this[this.tableMED_ERYTHROPOIETIN_EXEC.DRUG_ORDER_IDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsREMARKNull() {
                return this.IsNull(this.tableMED_ERYTHROPOIETIN_EXEC.REMARKColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetREMARKNull() {
                this[this.tableMED_ERYTHROPOIETIN_EXEC.REMARKColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class MED_ERYTHROPOIETINRowChangeEvent : global::System.EventArgs {
            
            private MED_ERYTHROPOIETINRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public MED_ERYTHROPOIETINRowChangeEvent(MED_ERYTHROPOIETINRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public MED_ERYTHROPOIETINRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class MED_ERYTHROPOIETIN_EXECRowChangeEvent : global::System.EventArgs {
            
            private MED_ERYTHROPOIETIN_EXECRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public MED_ERYTHROPOIETIN_EXECRowChangeEvent(MED_ERYTHROPOIETIN_EXECRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public MED_ERYTHROPOIETIN_EXECRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591